# Generated by Django 4.2.7 on 2023-11-25 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('category_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=30)),
                ('course_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='course/')),
                ('is_active', models.BooleanField(default=False)),
                ('course_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.coursecategory')),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
