# Generated by Django 4.2.7 on 2024-01-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
