# Generated by Django 4.2.7 on 2024-01-19 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_remove_reviews_likes_reviewrepley_reviewlikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewlikes',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_count', to='course.reviews'),
        ),
    ]
