# Generated by Django 4.2.7 on 2024-01-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_reviewlikes_is_liked_alter_reviewlikes_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewlikes',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
