# Generated by Django 4.2.7 on 2024-01-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_alter_reviewlikes_is_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewlikes',
            name='is_liked',
            field=models.BooleanField(default=True),
        ),
    ]
