# Generated by Django 4.2.7 on 2024-03-07 05:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_alter_reviewlikes_is_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursechapter',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Video uploads'),
        ),
    ]
