# Generated by Django 4.2.7 on 2023-11-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_useraccount_is_verified_useraccount_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='otp',
            field=models.CharField(max_length=10),
        ),
    ]
