# Generated by Django 4.2.7 on 2023-11-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_alter_useraccount_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='Bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='headline',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
