# Generated by Django 4.2.7 on 2023-11-29 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_useraccount_bio_useraccount_headline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='Bio',
            new_name='bio',
        ),
    ]
