# Generated by Django 4.2.7 on 2023-11-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_rename_bio_useraccount_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='sociallink',
            field=models.TextField(null=True),
        ),
    ]
