# Generated by Django 4.2.7 on 2023-11-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_useraccount_sociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_googleAuth',
            field=models.BooleanField(default=False),
        ),
    ]
