# Generated by Django 4.2.7 on 2023-11-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_useraccount_is_googleauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='image',
            field=models.ImageField(null=True, upload_to='users'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='phone',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
