# Generated by Django 4.2.7 on 2023-12-20 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_useraccount_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='InstructorFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(default=None, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
