# Generated by Django 4.2.7 on 2023-12-20 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0012_useraccount_experience_instructorfields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstructorFields',
        ),
    ]
