# Generated by Django 4.2.7 on 2023-12-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0014_alter_useraccount_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='refresh_token',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
