# Generated by Django 4.2.7 on 2023-12-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0016_alter_useraccount_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='access_token',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
    ]
