# Generated by Django 4.2.7 on 2024-01-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0017_useraccount_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='otp',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
