# Generated by Django 4.2.7 on 2024-01-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0018_alter_useraccount_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='otp_expiry',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
