# Generated by Django 4.2.7 on 2023-12-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='signature',
            field=models.CharField(max_length=200),
        ),
    ]
