# Generated by Django 4.2.7 on 2024-01-11 05:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_wallet_id_alter_wallet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ed450e24-fa96-44ad-bb63-96351b5e3b5a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
