# Generated by Django 4.2.7 on 2024-01-19 11:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='id',
            field=models.UUIDField(default=uuid.UUID('48df243a-5cc5-4323-88aa-d6ce485e6fd1'), editable=False, primary_key=True, serialize=False),
        ),
    ]
