# Generated by Django 4.2.7 on 2024-01-19 11:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e61b0a99-f453-452b-b369-fdcbce73fd7c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
