# Generated by Django 4.2.7 on 2024-01-19 11:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b06fcb26-4bf5-4a97-a33c-f995435be86e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
